### ISSUE TITLE
Can be installed on Visual Studio Enterprise 2017?

### ISSUE THREAD

**Issue by desaroger** [jjonescz/gtm-visualstudio-plugin#1]
Hi!

We are very intersted in use this plugin in our company, but currenty we are using Visual Studio Enterprise 2017 (version 15), and the vsix does't install.

I tried to update the vsixmanifest to make it work for version 15, but it seems to have a problem with the coreEditor prerequisite.

There is a workaround to make it work? thanks!

PS: I attached my version of the vsixmanifest with the modified versions. It let me install it, but shows the error "This extension cannot be installed because the following references are missing: Microsoft.VisualStudio.Component.CoreEditor"

**Comment by desaroger** [comment]
@jjonescz hello? Can you give me any clue why you closed this issue without giving any response?

**Comment by jjonescz** [comment]
I added support for Visual Studio 2017 in the latest version (`v1.11`).

**Comment by desaroger** [comment]
Wow! I tried it and works like a charm. Thank you very much!
